name: anytimeworkout
description: A new Flutter project.

publish_to: "none"

version: 6.4.0+7

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  in_app_review: ^2.0.8
  dart_ipify: ^1.1.1
  video_thumbnail: ^0.5.3
  loading_animation_widget: ^1.2.0+4
  blur: ^3.1.0
  metadata_fetch: ^0.4.1
  flutter_staggered_animations: ^1.1.1
  intl_phone_field: ^3.2.0
  cached_network_image: ^3.2.3
  bloc_concurrency: ^0.2.0
  country_state_city_picker: ^1.2.8
  image_picker: ^0.8.7+5
  numberpicker: ^2.0.1
  multiple_images_picker: ^1.0.1
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.0
  http: ^0.13.3 
  fluttericon: ^2.0.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.5
  carousel_slider: ^4.1.1
  form_bloc: ^0.30.0
  flutter_form_bloc: ^0.30.1
  google_sign_in: ^5.2.1
  flutter_secure_storage: ^5.0.2
  the_apple_sign_in: ^1.1.1
  flutter_screenutil: ^5.0.0
  geocoding: ^2.0.0
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.0.12
  fluttertoast: ^8.0.7
  ionicons: ^0.1.1
  shimmer: ^2.0.0
  photo_view: ^0.14.0
  flutter_typeahead: ^3.1.1
  pinput: ^1.2.2
  connectivity_plus: ^2.1.0
  device_info_plus: ^8.0.0
  flutter_image_compress: ^1.0.0
  mask_text_input_formatter: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  provider: ^6.0.5
  package_info: ^2.0.0
  flutter_facebook_auth: ^3.5.7
  minio: ^3.0.0
  share_plus: ^6.3.0
  webview_flutter: ^4.2.4
  progress_indicators: ^1.0.0
  rxdart: ^0.27.7
  google_maps_webservice: ^0.0.20-nullsafety.3
  flutter_google_places:
    path: vendor/flutter_google_places
  twilio_phone_verify: ^2.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0 
  is_lock_screen: ^2.0.0
  pubnub: ^4.2.1
  emoji_picker_flutter: ^1.3.1
  fl_country_code_picker: ^0.0.2+1
  flutter_phoenix: ^1.1.0
  path_provider: ^2.0.11
  nexmo_verify:
      path: vendor/nexmo_verify
  darq: ^1.2.1
  transloadit: ^0.2.0
  video_player: ^2.6.1
  mime: ^1.0.1
  chewie: ^1.5.0
  cryptography: ^2.5.0
  cryptography_flutter: ^2.0.2
  wechat_assets_picker: ^8.4.3
  file_picker: ^5.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_multi_formatter: ^2.11.1
  dart_style: ^2.3.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.1.4
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.6.3
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^9.1.4
  flutter_app_badger: ^1.5.0
  flutter_background_service: ^5.0.5
  shared_preferences: ^2.2.2
  location: ^5.0.3
  google_maps_flutter: ^2.3.0
  vibration: ^1.7.7
  
 
dependency_overrides:
  firebase_core_platform_interface: 5.0.0
  
dev_dependencies:
  # removed launch if needed comment minio package
  # flutter_launcher_icons: "^0.12.0"
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/translations/ar.json
    - assets/translations/en.json 
    - assets/.env
    - assets/icon/
    - assets/images/
    - assets/setup/
    - assets/images/men/
    - assets/images/women/
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
        - asset: assets/fonts/DMSans-Medium.ttf
