// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJTCHByv5_pxbEe3NpVwEAA3mg6yAT6fw',
    appId: '1:114080338719:web:fe4be29a3c1ca44663d62a',
    messagingSenderId: '114080338719',
    projectId: 'anytime-workout',
    authDomain: 'anytime-workout.firebaseapp.com',
    storageBucket: 'anytime-workout.appspot.com',
    measurementId: 'G-KW5LVPF67L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2HJPC4dy8qPeUyQmMug5Vm-pzHrUdGEQ',
    appId: '1:114080338719:android:a35c2daa9bd666a163d62a',
    messagingSenderId: '114080338719',
    projectId: 'anytime-workout',
    storageBucket: 'anytime-workout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoZ6HGBeMXL0Bal9XbOPYBAMcrzIKvE1w',
    appId: '1:114080338719:ios:34e7038447067c1d63d62a',
    messagingSenderId: '114080338719',
    projectId: 'anytime-workout',
    storageBucket: 'anytime-workout.appspot.com',
    androidClientId: '114080338719-5idrmchee9ounqsmljtqe07rka6f5nv3.apps.googleusercontent.com',
    iosClientId: '114080338719-cai643eonf9eni61051ck59i2hruv0vp.apps.googleusercontent.com',
    iosBundleId: 'com.aspirewebs.anytimeworkout',
  );
}
