import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

double? devicePixelRatio = ScreenUtil().pixelRatio;
double deviceWidth = 1.sw;
double deviceHeight = 1.sh;
double statusBarHeight = ScreenUtil().statusBarHeight;
double bottomBarHeight = ScreenUtil().bottomBarHeight;
double appBarHeight = AppBar().preferredSize.height;
double safeAreaHeight =
    deviceHeight - statusBarHeight - appBarHeight - bottomBarHeight;
double unitWidth = 1.w;
double unitHeight = 1.w;
double sideMenuWidth = 300.w;
double pageHPadding = 10.w;
double pageVPadding = 8.w;
double filterOptionTapWidth = 120.w;
double filterOptionTapSpace = 5.w;
double filterLocationInputWidth = 380.w;
double filterSubtypeOptionWidth = 180.w;
double filterRentFrequencyTapWidth = 100.w;
double filterRoomsOptionSize = 40.w;
double filterSimpleDropdownWidth = 160.w;
double filterCustomDropdownWidth = 380.w;
double filterMinMaxSelectDialogWidth = 300.w;
double filterSingleSelectDialogWidth = 280.w;
double filterMinMaxSelectDialogHeight = 380.w;
double filterSingleSelectDialogHeight = 460.w;
double filterSingleSelectDialogOptionWidth = 260.w;
double filterMinMaxSingleSelectDialogHeight = 240.w;
double filterCircleOptionWidth = 40.w;
double pageTitleSize = 18.sp;
double pageSubtitleSize = 14.sp;
double pageTextSize = 14.sp;
double pageSmallTextSize = 10.sp;
double pageIconSize = 16.sp;
double pageSmallIconSize = 12.sp;
double bottomSheetHPadding = 6.sp;
double bottomSheetVPadding = 4.sp;
double filterPriceOptionWidth = 120.sp;
double filterPriceOptionHeight = 280.sp;
double filterDialogActionButtonsWidth = 116.sp;
double textSmallSize = 11.sp;
double iconSize = 14.sp;
double buttonTextSized = 15.sp;
double drawerMenuItemSize = 17.sp;
double channelRowTextSize = 15.sp;
double linkTitleSize = 23.sp;
